Use pytest to run each test
mwperina/hirte-tests pull request #7
Opened 2023-04-19 22:14 UTC by mwperina

This will allow us to share the common code between tests.

Signed-off-by: Martin Perina <mperina@redhat.com>

2023-04-20 09:05 UTC, Yarboa reviewed
Interesting approach
Why do you plan to use pytest? 
The benefit of tmt is actually just for running the tests,
Did i miss some thing here? 

One more issue is the reporting mechanism 
Assume you have 3 tests running in pytest,
They are visible as single test, it is not good for interaction with QMS systesms

2023-04-20 09:05 UTC, Yarboa commented on tests/tier0/hirte-service-startup/main.fmf
> +  pytest -svv
I would advise to add Regex variable,
to control the tests.

Currently, what ever found by pytest.ini will be run
Assume the same infrastructure is used in hirte pipeline.

Tests running over there will be different from tests AutoSD image for example

2023-04-20 12:14 UTC, mwperina commented on tests/tier0/hirte-service-startup/main.fmf
> +  pytest -svv
Why? Here I want to perform actually 3 tests:

1. Check that hirte controller is running (and maybe respoding to requests)
2. Check that hirte-agent on node foo is running and successfully connected to to hirte (maybe even checking it's possible to fetch data from the node foo)
3. Check the same for hirte-agent on node bar

Of course other tests (for example proxy tests) will be located under different `tests/tier0/<PROXY TEST> directories`

2023-04-20 16:20 UTC, Yarboa commented on tests/tier0/hirte-service-startup/test_service_startup.py
> +from hirte_tests.common import fixtures
Once I reapplied the plugin import
There are many podmanclient API errors

2023-04-20 16:27 UTC, Yarboa commented on tests/tier0/hirte-service-startup/main.fmf
> +  pytest -svv
You are correct,
The problem is, the 3 pytests are run under one tmt test
as a result tmt junit xml, will look like this 

Actually the report will look like that 
?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="1" tests="1" time="0.0">
        <testsuite disabled="0" errors="0" failures="1" name="/plans/tier0" skipped="0" tests="1" time="0">
                <testcase name="/tests/tier0/hirte-service-startup">

but actuall you have 3 running tests

2023-04-20 16:30 UTC, Yarboa commented on tests/tier0/hirte-service-startup/main.fmf
> +  pytest -svv
Please refer here 
https://github.com/oamg/convert2rhel/blob/main/tests/integration/tier0/config-file/main.fmf
He splits the tests in the main file

2023-04-21 09:12 UTC, mwperina commented on tests/tier0/hirte-service-startup/test_service_startup.py
> +from hirte_tests.common import fixtures
With the last patch iteration it really works for me fine

2023-04-21 09:21 UTC, mwperina commented on tests/tier0/hirte-service-startup/main.fmf
> +  pytest -svv
No idea what QMS means.

If needed, we can add those description similar to above ...

2023-04-23 10:59 UTC, Yarboa requested changes
LGTM, but there are short fixes

2023-04-23 10:59 UTC, Yarboa commented on scripts/tests-setup.sh
> +fi
I would add here the, it is obviously need to be set up
Set up the REST API service

podman system service -t 0

this is why it was generating API errors here
https://github.com/mwperina/hirte-tests/pull/7#discussion_r1172790540

2023-04-23 19:03 UTC, mwperina commented on scripts/tests-setup.sh
> +if [ $? -ne 0]; then
Fixed

2023-04-23 19:04 UTC, mwperina commented on scripts/tests-setup.sh
> +fi
Why? This needs to be set up as a prerequisite. But unless I'm missing something it's required only on Fedora or CS9, on ubuntu it's enabled by default

2023-04-24 07:47 UTC, Yarboa commented on scripts/tests-setup.sh
> +fi
In Fedora it is required.
I assume check will not harm

2023-04-24 09:39 UTC, Yarboa approved these changes
LGTM,

2023-04-24 11:39 UTC, merged